/* GLOW CARS V8 - Stripe reservations */
(() => {
  const CHECKOUT_URL = 'https://hqsiglpdnylsfbideglc.supabase.co/functions/v1/create-reservation-checkout';
  const STYLE_ID = 'glow-reservation-style';
  const MODAL_ID = 'glow-reservation-modal';
  const css = `#${MODAL_ID}{position:fixed;inset:0;background:rgba(0,0,0,.86);z-index:10000;display:none;align-items:center;justify-content:center;padding:18px}#${MODAL_ID}.open{display:flex}.glow-res-box{width:min(560px,100%);max-height:92vh;overflow:auto;background:#111;border:1px solid #3a3a3a;border-radius:18px;padding:24px;box-shadow:0 20px 70px #000}.glow-res-box h2{margin:0 0 6px;color:#d8b36a}.glow-res-car{color:#fff;font-weight:800;margin-bottom:18px}.glow-res-note{color:#aaa;font-size:13px;line-height:1.55;margin:12px 0}.glow-res-box label{display:block;color:#ccc;font-size:13px;font-weight:700;margin:12px 0 6px}.glow-res-box input{width:100%;padding:12px;border-radius:9px;border:1px solid #3a3a3a;background:#080808;color:#fff;box-sizing:border-box}.glow-res-terms{background:#181818;border:1px solid #292929;border-radius:10px;padding:12px;color:#aaa;font-size:12px;line-height:1.55;margin-top:14px}.glow-res-check{display:flex!important;gap:9px;align-items:flex-start;margin-top:12px!important}.glow-res-check input{width:auto;margin-top:3px}.glow-res-actions{display:flex;gap:10px;margin-top:18px;flex-wrap:wrap}.glow-res-btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 16px;border-radius:9px;border:1px solid transparent;font-weight:900;cursor:pointer}.glow-res-primary{background:#d8b36a;color:#090909}.glow-res-secondary{background:transparent;color:#fff;border-color:#555}.glow-res-card-btn{display:block;width:100%;margin-top:14px;background:#d8b36a;color:#090909;border:0;border-radius:9px;padding:12px 14px;font-weight:900;cursor:pointer}.glow-res-card-btn:disabled{opacity:.55;cursor:not-allowed}.glow-res-error{color:#ff8f8f;font-size:13px;margin-top:10px}.logo img{width:190px!important;max-height:68px!important}.hero-panel img{width:98%!important;max-height:405px!important}@media(max-width:560px){.logo img{width:170px!important;max-height:64px!important}.hero-panel img{width:98%!important;max-height:270px!important}}`;
  function addStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=css;document.head.appendChild(s)}
  function getCarId(card){const m=(card.getAttribute('onclick')||'').match(/openGallery\((\d+),\s*(true|false)\)/);return m?Number(m[1]):null}
  function getCarName(card){return card.querySelector('h3')?.textContent?.trim()||'Vehículo GLOW CARS'}
  function isReserved(card){return /RESERVADO/i.test(card.querySelector('.badge')?.textContent||'')}
  function ensureModal(){if(document.getElementById(MODAL_ID))return;const m=document.createElement('div');m.id=MODAL_ID;m.innerHTML=`<div class="glow-res-box" role="dialog" aria-modal="true"><h2>Reservar vehículo</h2><div id="glowResCar" class="glow-res-car"></div><div class="glow-res-note"><b>Reserva: 300 €</b><br>La reserva es un pago anticipado del vehículo y un compromiso de compra. Si al venir a verlo se detecta un defecto importante del motor o un elemento mecánico relevante que no hubiera sido informado previamente, se podrá solicitar la devolución del importe tras su comprobación.</div><label>Nombre y apellidos<input id="glowResName" autocomplete="name"></label><label>Teléfono<input id="glowResPhone" type="tel" autocomplete="tel"></label><label>Email<input id="glowResEmail" type="email" autocomplete="email"></label><div class="glow-res-terms">Al continuar aceptas las condiciones de reserva indicadas arriba y confirmas que los 300 € constituyen un pago anticipado y un compromiso de compra sujeto a dichas condiciones.</div><label class="glow-res-check"><input id="glowResTerms" type="checkbox"> <span>Acepto las condiciones de reserva y el compromiso de compra.</span></label><div id="glowResMsg"></div><div class="glow-res-actions"><button class="glow-res-btn glow-res-primary" id="glowResPay">Continuar al pago · 300 €</button><button class="glow-res-btn glow-res-secondary" id="glowResClose">Cancelar</button></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)closeModal()});document.getElementById('glowResClose').onclick=closeModal;document.getElementById('glowResPay').onclick=startCheckout}
  let activeCarId=null;
  function openModal(id,name){ensureModal();activeCarId=id;document.getElementById('glowResCar').textContent=name;document.getElementById('glowResMsg').textContent='';document.getElementById(MODAL_ID).classList.add('open')}
  function closeModal(){document.getElementById(MODAL_ID)?.classList.remove('open')}
  async function startCheckout(){const name=document.getElementById('glowResName').value.trim(),phone=document.getElementById('glowResPhone').value.trim(),email=document.getElementById('glowResEmail').value.trim(),terms=document.getElementById('glowResTerms').checked,msg=document.getElementById('glowResMsg'),btn=document.getElementById('glowResPay');if(!name||!phone||!email||!terms){msg.textContent='Completa tus datos y acepta las condiciones.';msg.className='glow-res-error';return}btn.disabled=true;btn.textContent='Preparando pago…';try{const r=await fetch(CHECKOUT_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({car_id:activeCarId,name,phone,email,terms_accepted:terms})});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo iniciar la reserva.');location.href=data.url}catch(e){msg.textContent=e.message||'No se pudo iniciar la reserva.';msg.className='glow-res-error';btn.disabled=false;btn.textContent='Continuar al pago · 300 €'}}
  function addButtons(){document.querySelectorAll('#cars .car').forEach(card=>{if(card.dataset.glowReservation==='1')return;card.dataset.glowReservation='1';const id=getCarId(card);if(!id)return;const b=document.createElement('button');b.className='glow-res-card-btn';b.type='button';b.textContent=isReserved(card)?'🔒 Vehículo reservado':'🔐 Reservar por 300 €';b.disabled=isReserved(card);b.onclick=e=>{e.preventDefault();e.stopPropagation();if(!b.disabled)openModal(id,getCarName(card))};card.querySelector('.car-body')?.appendChild(b)})}
  function galleryButton(){const actions=document.querySelector('.gallery-actions');if(!actions||actions.querySelector('.glow-gallery-reserve'))return;try{if(typeof currentCar==='undefined'||!currentCar||currentSold)return;const b=document.createElement('button');b.className='btn gold glow-gallery-reserve';b.type='button';b.textContent=String(currentCar.estado||'').toLowerCase()==='reservado'?'🔒 Vehículo reservado':'🔐 Reservar por 300 €';b.disabled=String(currentCar.estado||'').toLowerCase()==='reservado';b.onclick=e=>{e.preventDefault();e.stopPropagation();if(!b.disabled)openModal(currentCar.id,currentCar['Marca-modelo']||'Vehículo GLOW CARS')};actions.appendChild(b)}catch(e){}}
  function showResult(){const p=new URLSearchParams(location.search);if(p.get('reserva')==='ok'){const n=document.createElement('div');n.style='position:fixed;left:12px;right:12px;bottom:18px;z-index:11000;background:#12351f;border:1px solid #2e9d5b;color:#fff;border-radius:12px;padding:16px;text-align:center;font-weight:800';n.textContent='✅ Reserva recibida. El pago de 300 € se ha registrado correctamente.';document.body.appendChild(n);setTimeout(()=>n.remove(),9000)}}
  addStyle();ensureModal();showResult();const obs=new MutationObserver(()=>{addButtons();galleryButton()});obs.observe(document.body,{childList:true,subtree:true});addButtons();galleryButton();
})();
